Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -25,7 +25,7 @@ jobs:
           echo "=== Project Contents ==="
           ls -R src/
           echo "=== Main Dart File ==="
-          find src -name main.dart || echo "Main.dart not found!"
+          find src -name .main.dart || echo "Main.dart not found!"
 
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
